import { Json } from './json';

export interface Children {
  Row: {
    id: string;
    name: string;
    birth_date: string | null;
    gender: string | null;
    city: string | null;
    photo_url: string | null;
    description: string | null;
    story: string | null;
    comments: string | null;
    is_sponsored: boolean;
    needs: Json[] | null;
    age: number | null;
    created_at: string | null;
    updated_at: string | null;
    end_date: string | null;
    location_id: number | null;
    photo_validated: boolean | null;
    sponsor_email: string | null;
    sponsor_facebook_url: string | null;
    sponsor_id: string | null; // Changed from number to string
    sponsor_name: string | null;
    sponsor_phone: string | null;
    sponsorship_id: string | null;
    sponsorship_status: string | null;
    sponsorships: string | null;
    start_date: string | null;
    status: string | null;
  };
  Insert: {
    id?: string;
    name: string;
    birth_date?: string | null;
    gender?: string | null;
    city?: string | null;
    photo_url?: string | null;
    description?: string | null;
    story?: string | null;
    comments?: string | null;
    is_sponsored?: boolean;
    needs?: Json[] | null;
    age?: number | null;
    created_at?: string | null;
    updated_at?: string | null;
    end_date?: string | null;
    location_id?: number | null;
    photo_validated?: boolean | null;
    sponsor_email?: string | null;
    sponsor_facebook_url?: string | null;
    sponsor_id?: string | null;
    sponsor_name?: string | null;
    sponsor_phone?: string | null;
    sponsorship_id?: string | null;
    sponsorship_status?: string | null;
    sponsorships?: string | null;
    start_date?: string | null;
    status?: string | null;
  };
  Update: {
    id?: string;
    name?: string;
    birth_date?: string | null;
    gender?: string | null;
    city?: string | null;
    photo_url?: string | null;
    description?: string | null;
    story?: string | null;
    comments?: string | null;
    is_sponsored?: boolean;
    needs?: Json[] | null;
    age?: number | null;
    created_at?: string | null;
    updated_at?: string | null;
    end_date?: string | null;
    location_id?: number | null;
    photo_validated?: boolean | null;
    sponsor_email?: string | null;
    sponsor_facebook_url?: string | null;
    sponsor_id?: string | null;
    sponsor_name?: string | null;
    sponsor_phone?: string | null;
    sponsorship_id?: string | null;
    sponsorship_status?: string | null;
    sponsorships?: string | null;
    start_date?: string | null;
    status?: string | null;
  };
}