export enum TableNames {
  CHILDREN = 'children',
  SPONSORS = 'sponsors',
  SPONSORSHIPS = 'sponsorships',
  CHILD_ASSIGNMENT_REQUESTS = 'child_assignment_requests',
  SPONSORSHIP_REQUESTS = 'sponsorship_requests',
  CHAT_ROOMS = 'chat_rooms',
  LOCATIONS = 'locations',
  AID_CATEGORIES = 'aid_categories',
  DONATIONS = 'donations',
  NOTIFICATIONS = 'notifications',
  MESSAGES = 'messages',
  PERMISSIONS = 'permissions',
  SPONSOR_LEVELS = 'sponsor_levels',
  BADGES = 'badges',
  ACTIVITIES = 'activities',
  ALBUM_MEDIA = 'album_media',
  COMMENTS = 'comments',
  EVENTS = 'events',
  FAVORITES = 'favorites',
  LOGS = 'logs',
  NEEDS = 'needs',
  REPORTS = 'reports',
  SETTINGS = 'settings',
  TAGS = 'tags',
  TASKS = 'tasks',
  TEMOIGNAGE = 'temoignage'
}